version: "3.9"

services:
  app:
    build: ./app
    ports:
      - 4000:4000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 4000
      PROXY_PORT: 80
      # MONGOURI: "mongodb://mongo:27017"
    # MONGOURI: "mongodb://admin:password@mongo:27017"
    depends_on:
      - redis
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "mahim"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - "80:3000"
      # - "3001:3001"
    restart: always
    depends_on:
      - app

  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - data:/data/db
  # environment:
  #   MONGO_INITDB_ROOT_USERNAME: "admin"
  #   MONGO_INITDB_ROOT_PASSWORD: "password"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
